version: '3'

services:

  front:
    build:
      context: ./front
    command: "npm run serve"
    volumes:
      - ./front/project-x:/app/:cached
      - ./front/project-x/node_modules:/app/node_modules
    ports:
      - "8080:8080"