version: '3'

services:

  front:
    build:
      context: ./front
    ports:
      - 8080:8080
    command: 'sh /app/start.sh'
    volumes:
      - ./front:/app/:cached
      - ./front/node_modules:/app/node_modules